# Generated by Django 3.2.5 on 2021-07-26 06:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('last_updated_by', models.UUIDField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('meta', models.JSONField(blank=True, default=dict, null=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
