# Generated by Django 3.2.5 on 2021-07-27 03:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInventory',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('last_updated_by', models.UUIDField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('meta', models.JSONField(blank=True, default=dict, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_inventory', to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
